// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateCustomer(arg1:services.CustomerCreateRequest):Promise<services.APIResponse>;

export function CreateLoan(arg1:services.LoanCreateRequest):Promise<services.APIResponse>;

export function CreateReferralCode(arg1:services.ReferralCodeCreateRequest):Promise<services.APIResponse>;

export function DeleteCustomer(arg1:string):Promise<services.APIResponse>;

export function DeleteDocument(arg1:string):Promise<services.APIResponse>;

export function DeleteReferralCode(arg1:string):Promise<services.APIResponse>;

export function DisburseLoan(arg1:string):Promise<services.APIResponse>;

export function GetAuditLog(arg1:string):Promise<services.APIResponse>;

export function GetAuditSummary(arg1:string):Promise<services.APIResponse>;

export function GetConfig():Promise<services.APIResponse>;

export function GetCustomer(arg1:string):Promise<services.APIResponse>;

export function GetDocument(arg1:string):Promise<services.APIResponse>;

export function GetDocumentFile(arg1:string):Promise<string>;

export function GetLoan(arg1:string):Promise<services.APIResponse>;

export function GetOverdueInstallments():Promise<services.APIResponse>;

export function GetPendingDocuments():Promise<services.APIResponse>;

export function GetPendingNotifications():Promise<services.APIResponse>;

export function GetReferralCode(arg1:string):Promise<services.APIResponse>;

export function GetSchedulerStatus():Promise<services.APIResponse>;

export function Greet(arg1:string):Promise<string>;

export function HealthCheck():Promise<services.APIResponse>;

export function ListAuditLogs(arg1:services.AuditLogListRequest):Promise<services.APIResponse>;

export function ListCustomers(arg1:services.CustomerListRequest):Promise<services.APIResponse>;

export function ListDocuments(arg1:services.DocumentListRequest):Promise<services.APIResponse>;

export function ListLoans(arg1:services.LoanListRequest):Promise<services.APIResponse>;

export function ListReferralCodes(arg1:services.ReferralCodeListRequest):Promise<services.APIResponse>;

export function LogAuditAction(arg1:services.AuditLogRequest):Promise<services.APIResponse>;

export function PayInstallment(arg1:services.InstallmentPaymentRequest):Promise<services.APIResponse>;

export function SeedDatabase():Promise<services.APIResponse>;

export function SendNotification(arg1:services.SendNotificationRequest):Promise<services.APIResponse>;

export function TestNotification(arg1:services.NotificationTestRequest):Promise<services.APIResponse>;

export function TriggerPendingNotifications():Promise<services.APIResponse>;

export function TriggerReminderNotifications():Promise<services.APIResponse>;

export function UpdateConfig(arg1:string):Promise<services.APIResponse>;

export function UpdateCustomer(arg1:string,arg2:services.CustomerUpdateRequest):Promise<services.APIResponse>;

export function UpdateLoan(arg1:string,arg2:services.LoanUpdateRequest):Promise<services.APIResponse>;

export function UpdateReferralCode(arg1:string,arg2:services.ReferralCodeUpdateRequest):Promise<services.APIResponse>;

export function ValidateReferralCode(arg1:string):Promise<services.APIResponse>;

export function VerifyDocument(arg1:services.DocumentVerifyRequest):Promise<services.APIResponse>;

export function Login(arg1:services.LoginRequest):Promise<services.APIResponse>;

export function Logout(arg1:string):Promise<services.APIResponse>;

export function ValidateSession(arg1:string):Promise<services.APIResponse>;

export function CreateUser(arg1:services.UserCreateRequest):Promise<services.APIResponse>;

export function GetUser(arg1:string):Promise<services.APIResponse>;

export function UpdateUser(arg1:string,arg2:services.UserUpdateRequest):Promise<services.APIResponse>;

export function ListUsers(arg1:services.UserListRequest):Promise<services.APIResponse>;

export function ChangePassword(arg1:services.ChangePasswordRequest):Promise<services.APIResponse>;

export function DeleteUser(arg1:string):Promise<services.APIResponse>;

export function UploadDocument(arg1:string,arg2:string,arg3:string,arg4:Array<number>):Promise<services.APIResponse>;
