// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['main']['App']['ChangePassword'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateLoan(arg1) {
  return window['go']['main']['App']['CreateLoan'](arg1);
}

export function CreateReferralCode(arg1) {
  return window['go']['main']['App']['CreateReferralCode'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteReferralCode(arg1) {
  return window['go']['main']['App']['DeleteReferralCode'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DisburseLoan(arg1) {
  return window['go']['main']['App']['DisburseLoan'](arg1);
}

export function GetAuditLog(arg1) {
  return window['go']['main']['App']['GetAuditLog'](arg1);
}

export function GetAuditSummary(arg1) {
  return window['go']['main']['App']['GetAuditSummary'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCustomer(arg1) {
  return window['go']['main']['App']['GetCustomer'](arg1);
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetDocumentFile(arg1) {
  return window['go']['main']['App']['GetDocumentFile'](arg1);
}

export function GetLoan(arg1) {
  return window['go']['main']['App']['GetLoan'](arg1);
}

export function GetOverdueInstallments() {
  return window['go']['main']['App']['GetOverdueInstallments']();
}

export function GetPendingDocuments() {
  return window['go']['main']['App']['GetPendingDocuments']();
}

export function GetPendingNotifications() {
  return window['go']['main']['App']['GetPendingNotifications']();
}

export function GetReferralCode(arg1) {
  return window['go']['main']['App']['GetReferralCode'](arg1);
}

export function GetReferralPerformance(arg1) {
  return window['go']['main']['App']['GetReferralPerformance'](arg1);
}

export function GetSchedulerStatus() {
  return window['go']['main']['App']['GetSchedulerStatus']();
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ListAuditLogs(arg1) {
  return window['go']['main']['App']['ListAuditLogs'](arg1);
}

export function ListCustomers(arg1) {
  return window['go']['main']['App']['ListCustomers'](arg1);
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function ListLoans(arg1) {
  return window['go']['main']['App']['ListLoans'](arg1);
}

export function ListReferralCodes(arg1) {
  return window['go']['main']['App']['ListReferralCodes'](arg1);
}

export function ListUsers(arg1) {
  return window['go']['main']['App']['ListUsers'](arg1);
}

export function LogAuditAction(arg1) {
  return window['go']['main']['App']['LogAuditAction'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function PayInstallment(arg1) {
  return window['go']['main']['App']['PayInstallment'](arg1);
}

export function SeedDatabase() {
  return window['go']['main']['App']['SeedDatabase']();
}

export function SendNotification(arg1) {
  return window['go']['main']['App']['SendNotification'](arg1);
}

export function TestNotification(arg1) {
  return window['go']['main']['App']['TestNotification'](arg1);
}

export function TriggerPendingNotifications() {
  return window['go']['main']['App']['TriggerPendingNotifications']();
}

export function TriggerReminderNotifications() {
  return window['go']['main']['App']['TriggerReminderNotifications']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateLoan(arg1, arg2) {
  return window['go']['main']['App']['UpdateLoan'](arg1, arg2);
}

export function UpdateReferralCode(arg1, arg2) {
  return window['go']['main']['App']['UpdateReferralCode'](arg1, arg2);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2);
}

export function UploadDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3, arg4);
}

export function ValidateReferralCode(arg1) {
  return window['go']['main']['App']['ValidateReferralCode'](arg1);
}

export function ValidateSession(arg1) {
  return window['go']['main']['App']['ValidateSession'](arg1);
}

export function VerifyDocument(arg1) {
  return window['go']['main']['App']['VerifyDocument'](arg1);
}
